services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql

  atlas:
    image: arigaio/atlas:latest
    container_name: atlas
    networks:
      - db
    depends_on:
      - postgres-db
    volumes:
      - ./db/migrations/:/migrations
    entrypoint: ["sleep","infinity"]

networks:
  db:

volumes:
  postgres_data:
